version: '3.8'

services:
  postgres:
    image: postgres:15  # Use the latest stable version of PostgreSQL
    container_name: postgres_auth_service
    environment:
      POSTGRES_USER: dockeruser  # Replace with your desired username
      POSTGRES_PASSWORD: password  # Replace with your desired password
      POSTGRES_DB: auth_service  # Replace with your desired database name
    ports:
      - "5432:5432"  # Host:Container port mapping
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent storage

volumes:
  postgres_data:
